# Generated by Django 2.2.4 on 2022-07-04 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cook_app', '0002_auto_20220630_0527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient',
        ),
    ]
