# Generated by Django 2.2.4 on 2022-07-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook_app', '0003_remove_recipe_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(blank=True, to='cook_app.Ingredient'),
        ),
    ]
