# Generated by Django 2.2.4 on 2022-07-05 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cook_app', '0006_auto_20220704_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='cook_app.Chef'),
        ),
        migrations.DeleteModel(
            name='Cook',
        ),
    ]
