# Generated by Django 2.2 on 2022-07-12 02:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cook_app', '0007_auto_20220705_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
